### ISSUE TITLE
恶心的百度，还是随机出现一些广告与结果完全样式的DOM

### ISSUE THREAD

**Issue by cipchk** [pancao/baidulite#4]
所以……我加了两条。

``` css
.c-container {
    position: relative;
}
.c-container .f13 span.m,
.gnaduS {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.35);
    color: #f50;
    font-size: 40px;
    text-align: center;
}
```

效果：

![效果图片](http://im2.96weixin.com/uploads/userup/image/20161012/1476260220473779.png)
